.env
.github/workflows/build-and-run-tests.yml
.github/workflows/build-installers.yml
.gitignore
LICENSE.txt
README.md
download-javafx.sh

This adds CI support on Github.  It also acts as a test run for pull requests into the repository.

GitHub additions

---

.github/workflows/build-and-run-tests.yml
README.md
bluej/build.xml
greenfoot/build.xml

We need to state how to actually build and run BlueJ and Greenfoot.

Fix ant run targets and improve README

---

bluej/build.gradle
bluej/src/main/java/bluej/debugger/jdi/JdiThread.java
bluej/src/main/java/bluej/editor/base/TextLine.java
bluej/src/main/java/bluej/editor/flow/FlowIndent.java
bluej/src/main/java/bluej/editor/flow/JavaSyntaxView.java
bluej/src/main/java/bluej/editor/flow/MultilineStringTracker.java
bluej/src/main/java/bluej/stride/framedjava/frames/TryFrame.java
bluej/src/main/java/bluej/terminal/Terminal.java
bluej/src/test/java/bluej/editor/flow/TestBasicEditorDisplay.java

This fixes multiple different small bugs in BlueJ.  See individual commits for more details.

Multiple small bug fixes

---

bluej/src/main/java/bluej/Main.java
bluej/src/main/java/bluej/parser/EditorParser.java
boot/src/main/java/bluej/Boot.java

Also clean up some old file handling code.
Fixes #1265

Fix bug with invalid static imports

---

.github/workflows/build-installers.yml
bluej/package/build.xml
boot/src/main/java/bluej/Boot.java
version.properties

A couple of small fixes for the Mac installer and to put a JUnit dependency on the classpath for the user VM.

Fix Mac installer and JUnit classpath

---

bluej/package/gfdebianfiles-bundled/greenfoot
boot/src/main/java/bluej/Boot.java
greenfoot/build.gradle
version.properties

Linux installer was broken, and sharing scenarios to the website wasn't working.

Fix a couple of Greenfoot issues

---

bluej/build.gradle
bluej/package/build.xml
bluej/package/winlaunch/bjmanifest.xml
bluej/package/winlaunch/bluej-version.rc
bluej/package/winlaunch/gfmanifest.xml
bluej/package/winlaunch/greenfoot-version.rc
boot/build.gradle
version.properties

Hopefully this will finally fix Windows, without breaking the other OSes.

Fix issues with bundling JavaFX on Windows in BlueJ

---

bluej/package/greenfoot-build.xml

Yet another fix for the location of the Greenfoot common classes and API doc

---

bluej/package/greenfoot-build.xml
greenfoot/build.gradle

Added a urlsRC task to Greenfoot Gradle

---

bluej/lib/bluej.defs
bluej/package/greenfoot-build.xml
version.properties

More fixes for the fragile bundling code.

Fix bundling on Mac and Linux

---

bluej/lib/bluej.defs
bluej/lib/english/labels
bluej/lib/stylesheets/dialogs.css
bluej/src/main/java/bluej/editor/base/LineDisplay.java
bluej/src/main/java/bluej/editor/base/TextLine.java
bluej/src/main/java/bluej/groupwork/git/GitHistoryCommand.java
bluej/src/main/java/bluej/pkgmgr/AboutDialogTemplate.java
bluej/src/main/java/bluej/pkgmgr/PkgMgrFrame.java
bluej/src/main/java/bluej/pkgmgr/actions/JavaFXAPIHelpAction.java
bluej/src/main/java/bluej/terminal/Terminal.java
bluej/src/main/java/bluej/utility/Utility.java
boot/src/main/java/bluej/Boot.java
greenfoot/src/main/java/greenfoot/guifx/GreenfootStage.java

This is various small fixes for BlueJ.  I was going to wait until they were all finished, but I think that will end up too large.  So I'm sending this set, then I'll work on the last couple of issues.

Multiple minor fixes for BlueJ

---

bluej/src/main/java/bluej/editor/fixes/SuggestionList.java
bluej/src/main/java/bluej/parser/ParseUtils.java
bluej/src/test/java/bluej/parser/CompletionTest3.java

I fixed the issue we discussed with local variables that shadow fields.  In doing that I found a couple more bugs, so I added some tests to show them up and fixed them too.

Autocomplete local variable fixes

---

.gitignore
bluej/build.gradle
bluej/lib/stylesheets/dialogs.css
bluej/src/main/java/bluej/Config.java
bluej/src/main/java/bluej/pkgmgr/AboutDialogTemplate.java
bluej/src/main/java/bluej/stride/framedjava/frames/SwitchFrame.java
bluej/src/main/java/bluej/stride/framedjava/frames/TryFrame.java

The few changes we discussed.  The build ID is just the short version of the Git commit; when we run (or build installer) we write a buildid.txt file with the latest commit ID, and then you can see it in the about dialog or the debug log.

Fix switch frame, add build ID

---

bluej/lib/stylesheets/debugger.css
bluej/lib/stylesheets/pkgmgrframe.css
bluej/src/main/java/bluej/debugmgr/ExecControls.java
bluej/src/main/java/bluej/debugmgr/objectbench/ObjectWrapper.java
bluej/src/main/java/bluej/terminal/TerminalTextPane.java

See individual commits for more details, but fixes issues with debugger, object highlighting while debugging, and new terminal background feature.

Fix various small bugs in 5.3.0rc1

---

bluej/src/main/java/bluej/terminal/TerminalTextPane.java

Fixed a bug where the terminal would show an empty tooltip when hovering over a region with no marking.  Now it will not show up the tooltip in that case.

Fix a terminal tooltip

---

bluej/src/main/java/bluej/stride/generic/TopLevelDocumentMultiCanvasFrame.java
bluej/src/main/java/bluej/utility/javafx/HangingFlowPane.java

This is the fix for the infinite layout issue I mentioned earlier today.  The comment in TopLevelDocumentMultiCanvasFrame will hopefully explain the main issue well.  The other change (adding the cache) is something that helped a little along the way, so I thought I'd keep that change even though it's not the cause of the major issue.

Fix Stride lag

---

.env
.github/workflows/build-installers.yml

Fixes for https://bugs.openjdk.org/browse/JDK-8319669 and https://bugs.openjdk.org/browse/JDK-8320194

Bumped the JDK version to 21.0.4, which should include some bug fixes

---

bluej/src/main/java/bluej/terminal/Terminal.java
version.properties

Reverts k-pet-group/BlueJ-Greenfoot#2379
We decided that since this did not hide the whole message, it's best to show all of it rather than part of it.

Revert "Suppressed a JavaFX exception that Michael sees on his Mac when opening BlueJ projects"

---

bluej/package/sign-mac.sh

This should fix building on Mac.

Fixed the printing of the log and signed the problematic jnilib file

---

bluej/src/main/java/bluej/groupwork/git/GitRepository.java
version.properties

Another change to try to fix Git with SSH and passwords.

Fix Git with SSH (again!)

---

bluej/lib/english/labels
bluej/src/main/java/bluej/Main.java
bluej/src/main/java/bluej/editor/base/BaseEditorPane.java
bluej/src/main/java/bluej/editor/base/LineDisplay.java
bluej/src/main/java/bluej/editor/base/MarginAndTextLine.java
bluej/src/main/java/bluej/editor/flow/FlowEditor.java
bluej/src/main/java/bluej/editor/flow/FlowEditorPane.java
bluej/src/main/java/bluej/prefmgr/PrefMgr.java
bluej/src/main/java/bluej/terminal/TerminalTextPane.java

Several improvements, one per commit.  Most notable is the last one, which allows for "go to definition" support in the Java editor.  (We had this in Stride already but we don't share code as Stride's is more featured and better: it knows if it is a type or method name, currently the new Java one just looks for class names.)

Several BlueJ improvements

---

bluej/lib/english/labels
bluej/lib/stylesheets/inspectors.css
bluej/src/main/java/bluej/debugmgr/inspector/Inspector.java
bluej/src/main/java/bluej/debugmgr/inspector/ObjectInspector.java

Including a button to copy the content to clipboard.
Fixes #2208.
This is quite small, but it's unrelated to the two other, larger items that I want to do next, so I'm putting it as its own PR.

When inspecting strings, added their content in a new pane in the inspector

---

bluej/lib/english/labels
bluej/lib/stylesheets/dialogs.css
bluej/src/main/java/bluej/debugmgr/Invoker.java
bluej/src/main/java/bluej/debugmgr/codepad/CodePad.java
bluej/src/main/java/bluej/debugmgr/objectbench/ObjectWrapper.java
bluej/src/main/java/bluej/pkgmgr/NewTextFileDialog.java
bluej/src/main/java/bluej/pkgmgr/PkgMgrFrame.java
bluej/src/main/java/bluej/utility/javafx/dialog/InputDialog.java
bluej/src/test/java/bluej/parser/TextParserTest.java
greenfoot/src/main/java/greenfoot/guifx/GreenfootStage.java

Add re-run button as discussed, and also change the New Text File feature to New CSS/Text, with a dropdown for the extension.

Add re-run button

---

bluej/lib/english/labels
bluej/package/winlaunch/bjmanifest.xml
bluej/package/winlaunch/bluej-version.rc
bluej/package/winsetup/bluej.wxs
bluej/src/main/java/bluej/Main.java
bluej/src/main/java/bluej/extensions2/BPackage.java
bluej/src/main/java/bluej/pkgmgr/ClassContent.java
bluej/src/main/java/bluej/pkgmgr/NewClassDialog.java
bluej/src/main/java/bluej/pkgmgr/PkgMgrFrame.java
bluej/src/main/java/bluej/pkgmgr/ProjectUtils.java
bluej/src/main/java/bluej/pkgmgr/target/ClassTarget.java
bluej/src/main/java/bluej/pkgmgr/target/actions/CreateTestAction.java
bluej/src/main/java/bluej/pkgmgr/target/role/ClassRole.java
bluej/src/main/java/bluej/prefmgr/InterfacePanel.java
bluej/src/main/java/bluej/prefmgr/PrefMgr.java
bluej/src/main/java/bluej/stride/framedjava/ast/Loader.java
bluej/src/main/java/bluej/terminal/Terminal.java
bluej/src/main/java/bluej/utility/BlueJFileReader.java
boot/src/main/java/bluej/Boot.java
greenfoot/src/main/java/greenfoot/export/JarCreator.java
version.properties

As discussed recently, several improvements to BlueJ:
- Allow setting the config for "reopen last projects" in the preferences dialog
- Add an "always on top" option in the terminal (deliberately not remembered across sessions)
- Add an empty/full dropdown to the new-class dialog to let you have an empty class if you prefer.  (Remembered across sessions.)

BlueJ feature improvements

---

bluej/src/main/java/bluej/editor/base/LineDisplay.java
bluej/src/main/java/bluej/editor/base/MarginAndTextLine.java
bluej/src/main/java/bluej/editor/flow/FlowEditorPane.java
bluej/src/main/java/bluej/editor/flow/HoleDocument.java
bluej/src/main/java/bluej/pkgmgr/ClassContent.java
bluej/src/test/java/bluej/parser/TextParserTest.java

Fixes a bug with exceptions not displaying in the terminal, and a few other small fixes.  Explanations are in the individual commit comments.

Some more BlueJ improvements

---

bluej/package/sign-mac.sh
bluej/src/main/java/bluej/editor/flow/FlowEditorPane.java
bluej/src/main/java/bluej/editor/flow/HoleDocument.java

Very small PR; remove work-around for Adoptium bug that has been fixed.

Fix mac build and add comment

---

bluej/lib/bluej.defs
bluej/src/main/java/bluej/editor/base/BaseEditorPane.java

Fix line number default, and ctrl-scroll direction.

Two tiny fixes for the latest changes
