k-pet-group/BlueJ-Greenfoot

- bluej/src/main/java/bluej/editor/stride/BirdseyeManager.java
- bluej/src/main/java/bluej/editor/stride/FrameEditorTab.java
- bluej/src/main/java/bluej/stride/framedjava/frames/AssignFrame.java
- bluej/src/main/java/bluej/stride/framedjava/frames/CallFrame.java
- bluej/src/main/java/bluej/stride/framedjava/frames/CaseFrame.java
- bluej/src/main/java/bluej/stride/framedjava/frames/ClassFrame.java
- bluej/src/main/java/bluej/stride/framedjava/frames/CommentFrame.java
- bluej/src/main/java/bluej/stride/framedjava/frames/ConstructorFrame.java
- bluej/src/main/java/bluej/stride/framedjava/frames/ForeachFrame.java
- bluej/src/main/java/bluej/stride/framedjava/frames/IfFrame.java
- bluej/src/main/java/bluej/stride/framedjava/frames/ImportFrame.java
- bluej/src/main/java/bluej/stride/framedjava/frames/InheritedMethodFrame.java
- bluej/src/main/java/bluej/stride/framedjava/frames/MethodProtoFrame.java
- bluej/src/main/java/bluej/stride/framedjava/frames/NormalMethodFrame.java
- bluej/src/main/java/bluej/stride/framedjava/frames/ReturnFrame.java
- bluej/src/main/java/bluej/stride/framedjava/frames/SwitchFrame.java
- bluej/src/main/java/bluej/stride/framedjava/frames/ThrowFrame.java
- bluej/src/main/java/bluej/stride/framedjava/frames/VarFrame.java
- bluej/src/main/java/bluej/stride/framedjava/frames/WhileFrame.java
- bluej/src/main/java/bluej/stride/generic/Frame.java
- bluej/src/main/java/bluej/stride/generic/FrameCursor.java
I discovered while preparing the talk for next week that birds eye mode in Stride didn't work with screen readers.  This fixes it to read out the text of the selected frame as you traverse up and down.
> Made birds eye mode work with screen readers.

- bluej/lib/bluej.defs
This small change is in relation to a support email we received about monospace font display in the terminal.
The related property in the bluej.defs file is no longer relevant.
(For info, changes to the terminal font can be done via the CSS files.)
> Removed unused properties in defs file (for terminal font)

- bluej/src/main/java/bluej/debugmgr/codepad/CodePad.java
- bluej/src/main/java/bluej/editor/flow/FlowEditor.java
- bluej/src/test/java/bluej/editor/flow/TestBasicEditorInteraction.java
Fix bugs with the "show source in BlueJ" link that we add to the Javadoc, another bug with the codepad and the terminal, and a test failure.
Fixes #1324
Fixes #2217 
Fixes #1255
> Fix show source link, and other fixes

- bluej/lib/stylesheets/flow.css
- bluej/src/main/java/bluej/debugmgr/ExecControls.java
- bluej/src/main/java/bluej/debugmgr/codepad/CodePad.java
- bluej/src/main/java/bluej/editor/base/BaseEditorPane.java
- bluej/src/main/java/bluej/editor/base/MarginAndTextLine.java
- bluej/src/main/java/bluej/editor/fixes/FixDisplayManager.java
- bluej/src/main/java/bluej/editor/flow/FlowEditor.java
- bluej/src/main/java/bluej/editor/flow/Info.java
- bluej/src/main/java/bluej/editor/flow/StatusLabel.java
- bluej/src/main/java/bluej/prefmgr/PrefMgr.java
- bluej/src/main/java/bluej/terminal/Terminal.java
Made the font size of line numbers change as the main editor font size changes, and added an item to the margin context menu to allow toggling a breakpoint (which you can do just by left-clicking there, but it makes sense to have a context menu item too, since we do have a context menu there).
Fixes #435 
Fixes #1256
> Fix line numbers to change size, add context menu to toggle breakpoint

- bluej/lib/english/dialogues
- bluej/lib/stylesheets/pkgmgrframe.css
- bluej/src/main/java/bluej/debugmgr/ExecControls.java
- bluej/src/main/java/bluej/debugmgr/codepad/CodePad.java
- bluej/src/main/java/bluej/editor/flow/FlowEditor.java
- bluej/src/main/java/bluej/pkgmgr/ProjectUtils.java
Fixes a bug with errors not showing, adds a feature to allow termination of the program directly from the dialog about code still executing, and adds a feature to make clear in the codepad that the program has been terminated.
Fixes #1340 
Fixes #1257
Fixes #908
> Fix several minor bugs

- bluej/build.gradle
Without this, the generic installer is not building on Linux and thus it's missing from the automatically built zip of them all.
> Added a target to the Linux Gradle build to build the generic installer.

- bluej/package/winsetup/bluej.wxs
- boot/build.gradle
There was an error in the updateVersionNumber task which meant that during the build, the MSI details were not updated correctly.  Thus the 5.2.0 MSI accidentally had internal version number of 5.1.0 and the old GUID too.
> Fix version number in the MSI build

- bluej/package/installer.props
… rather than the old bluej.jar which no longer contains that class.
Fixes #2232
> Fixed the generic installer to use boot.jar for the bluej.Boot class

- bluej/src/main/java/bluej/prefmgr/MiscPrefPanel.java
- bluej/src/main/java/bluej/prefmgr/MiscPrefPanelItem.java
- bluej/src/main/java/bluej/prefmgr/PrefMgr.java
- bluej/src/main/java/bluej/prefmgr/PrefMgrDialog.java
- greenfoot/labels/english/greenfoot/greenfoot-labels
- greenfoot/src/main/java/greenfoot/core/ProjectManager.java
- greenfoot/src/main/java/greenfoot/guifx/GreenfootStage.java
- greenfoot/src/main/java/greenfoot/guifx/soundrecorder/SoundRecorderControls.java
- greenfoot/src/main/java/greenfoot/sound/MicLevelGrabber.java
- greenfoot/src/main/java/greenfoot/sound/SoundClip.java
- greenfoot/src/main/java/greenfoot/sound/SoundFactory.java
- greenfoot/src/main/java/greenfoot/sound/SoundPreferencePanel.java
- greenfoot/src/main/java/greenfoot/sound/SoundRecorder.java
- greenfoot/src/main/java/greenfoot/sound/SoundStream.java
- greenfoot/src/main/java/greenfoot/sound/SoundUtils.java
This adds an option in the sound recorder window and the general preferences to select an audio device for input and output (independently).  This is then saved into the local preferences so that it persists across sessions.
Fixes #2244 
Fixes #2245
> Add the ability to select input/output audio devices for Greenfoot

- bluej/src/main/java/bluej/pkgmgr/AboutDialogTemplate.java
- bluej/src/main/java/bluej/pkgmgr/PkgMgrFrame.java
For the translators TableView, the columns' preferred width being set was supposed to avoid showing a scrollbar, but it shows anyway, and adding the Korean translators made the content even larger; so we now let JavaFX handle it.
> Added the Korean translators in About + removed table columns preferred widths

- bluej/src/main/java/bluej/parser/InfoParser.java
- bluej/src/main/java/bluej/parser/symtab/ClassInfo.java
- bluej/src/main/java/bluej/pkgmgr/Package.java
- bluej/src/main/java/bluej/pkgmgr/dependency/Dependency.java
- bluej/src/main/java/bluej/pkgmgr/dependency/ExtendsDependency.java
- bluej/src/main/java/bluej/pkgmgr/dependency/ImplementsDependency.java
- bluej/src/main/java/bluej/pkgmgr/dependency/PermitsDependency.java
- bluej/src/main/java/bluej/pkgmgr/dependency/UsesDependency.java
- bluej/src/main/java/bluej/pkgmgr/dependency/package-info.java
- bluej/src/main/java/bluej/pkgmgr/target/ClassTarget.java
- bluej/src/main/java/bluej/pkgmgr/target/DependentTarget.java
- version.properties
This mainly adds support for permits dependencies in the 4th and 5th commit, but first it does some tidy-up in the 1st to 3rd commits for preparation.  As mentioned, this doesn't actually seem to solve the issue with the compiler error appearing in the wrong place but I think it's probably still worth including for when the JDK behaves more sensibly.  I'll then build the next (and hopefully final!) Greenfoot RC.  And I'll see if I can make an easy small example of the JDK putting the error in the wrong place.
> Add support for permits dependencies

- bluej/src/main/java/bluej/editor/EditorWatcher.java
- bluej/src/main/java/bluej/editor/flow/FlowEditor.java
- bluej/src/main/java/bluej/extensions2/BlueJ.java
- bluej/src/main/java/bluej/extensions2/Extension.java
- bluej/src/main/java/bluej/extensions2/ExtensionBridge.java
- bluej/src/main/java/bluej/extensions2/MenuGenerator.java
- bluej/src/main/java/bluej/extmgr/ClassExtensionMenu.java
- bluej/src/main/java/bluej/extmgr/ExtensionMenu.java
- bluej/src/main/java/bluej/extmgr/ExtensionMenuSingle.java
- bluej/src/main/java/bluej/extmgr/ExtensionWrapper.java
- bluej/src/main/java/bluej/extmgr/ExtensionsManager.java
- bluej/src/main/java/bluej/extmgr/ExtensionsMenuManager.java
- bluej/src/main/java/bluej/extmgr/ObjectExtensionMenu.java
- bluej/src/main/java/bluej/extmgr/PackageExtensionMenu.java
- bluej/src/main/java/bluej/extmgr/ToolsExtensionMenu.java
- bluej/src/main/java/bluej/pkgmgr/target/ClassTarget.java
The main change here is really to add a new method that allows BlueJ extensions to add one *or more* menu items to the Java editor context menu (when the user right clicks in the Java editor).  This involved a bit more changes than it first appears, because the existing infrastructure for menu items in extensions only supported a single menu item.  So I generalised it to support multiple items, then added a helper class to support all the existing single-item methods in the extensions.  You can see this more easily if you break it down by commit.
> Allow extensions to add Java editor context menu items

- bluej/package/greenfoot-build.xml
Image was not being included in the JAR, which caused an error when you tried to run it.
> Added missing image to generic Greenfoot installer.

- bluej/package/greenfoot-installer.props
- boot/src/main/java/bluej/Boot.java
Fixes two classpath issues: one change to use boot.jar not bluej.jar, and one change to restore some old code for detecting the JavaFX path.  I removed it, but now I realise we still need it for the generic installer.
> Fix issues with generic installer for Greenfoot

- bluej/src/main/java/bluej/editor/stride/FrameEditorTab.java
- bluej/src/main/java/bluej/extmgr/ExtensionMenuSingle.java
- bluej/src/main/java/bluej/extmgr/ExtensionWrapper.java
- bluej/src/main/java/bluej/stride/framedjava/frames/ClassFrame.java
- version.properties
I noticed a couple of bugs in BlueJ 5.2.1RC1.  The main one which has to be fixed is that the context menu was failing to show when you right-clicked a class in the diagram.  This was because of some incorrect logic in the change to the extensions API which interacted badly with the Submitter extension.  The other bug was that Stride was sometimes saying "you are in class null" for the accessibility code, which is a subtle fix where we need to set the property rather than the label.
After this I'll send out RC2.
> Fix BlueJ context menu and Stride accessibility bugs

- boot/src/main/java/bluej/Boot.java
- version.properties
In fixing the generic installer JavaFX path, I broke the Windows JavaFX path location.  Ubuntu was unaffected because it lists the JARs individually, and Mac was unaffected because it uses appbundler and uses javafx-*.jar.
> Fix JavaFX path location on Windows

- bluej/package/greenfoot-build.xml
- bluej/src/main/java/bluej/Main.java
- greenfoot/src/main/java/greenfoot/Actor.java
- greenfoot/src/main/java/greenfoot/ActorVisitor.java
- greenfoot/src/main/java/greenfoot/core/Simulation.java
- version.properties
This is three separate changes.  It fixes the common classes not being packaged (will need testing once Github builds an RC), adds support for the news mechanism and adds a new sleepFor method (both as discussed in the meeting yesterday).
Fixes #2273
> Greenfoot: fix common classes, add news, add sleepFor

- bluej/src/main/java/bluej/prefmgr/MiscPrefPanel.java
I was saving this change for BlueJ but actually it applies for Greenfoot too, so we should put it in the upcoming release.
> Got rid of the preference section for the documentation URL.

- bluej/lib/tutorial/package.bluej
- bluej/src/main/java/bluej/editor/fixes/SuggestionList.java
- bluej/src/main/java/bluej/editor/flow/FlowEditor.java
- bluej/src/main/java/bluej/editor/flow/FlowErrorManager.java
- bluej/src/main/java/bluej/editor/stride/FrameEditor.java
- bluej/src/main/java/bluej/parser/EditorParser.java
- bluej/src/main/java/bluej/parser/ParseUtils.java
- bluej/src/main/java/bluej/parser/nodes/FieldNode.java
- bluej/src/main/java/bluej/parser/nodes/JavaParentNode.java
- bluej/src/main/java/bluej/parser/nodes/MethodNode.java
- bluej/src/main/java/bluej/parser/nodes/VariableDeclaration.java
- bluej/src/test/java/bluej/parser/CompletionTest.java
- bluej/src/test/java/bluej/parser/CompletionTest3.java
Add support in the Java autocomplete for locally declared variables (including parameters, local variables, for-loop and for-each loop variables, and instanceof variables).
Fixes #2303
> Add autocomplete support for local variables

- bluej/src/main/java/bluej/extensions2/BConstructor.java
- bluej/src/main/java/bluej/extensions2/BMethod.java
- bluej/src/main/java/bluej/extensions2/DirectInvoker.java
- bluej/src/main/java/bluej/extensions2/InvocationArgumentException.java
- bluej/src/main/java/bluej/extensions2/InvocationErrorException.java
This is the fix for threading to match with mainrunner.  It's a bit of a nightmare, to be honest; the methods need to block on the result while off-thread, but they need to do some bits on the FX thread both before and after that.  And there might be exceptions which need to be carried around and rethrown on another thread.  It passes the thread checker and it seems to now work with the adjusted mainrunner, so hopefully that means it's all done correctly!
> Corrected the threading behaviour of invoking constructors and methods from the extension API.

- bluej/src/main/java/bluej/BlueJEvent.java
- bluej/src/main/java/bluej/debugmgr/ExecutionEvent.java
- bluej/src/main/java/bluej/debugmgr/codepad/CodePad.java
- bluej/src/main/java/bluej/debugmgr/objectbench/ResultWatcherBase.java
- bluej/src/main/java/bluej/editor/base/LineDisplay.java
- bluej/src/main/java/bluej/editor/flow/FlowEditorPane.java
- bluej/src/main/java/bluej/extensions2/DirectInvoker.java
- bluej/src/main/java/bluej/extensions2/event/InvocationFinishedEvent.java
- bluej/src/main/java/bluej/terminal/Terminal.java
- bluej/src/main/java/bluej/terminal/TerminalTextPane.java
- tools.properties
This adds a change recently discussed in the meeting/on the Blueroom.  It borrows BlueJ's scope highlighting mechanism to add grey section markers around each bit of output in the terminal, showing which method call it is from.  It also adds a tooltip on hover, which tells you what the method call was.  Finally, it clears the stderr pane on each method call (Michael requested this).
> Add sections to BlueJ terminal to divide up different method calls

- bluej/lib/english/moe.help
- bluej/lib/german/moe.help
- bluej/src/main/java/bluej/editor/flow/FlowActions.java
You can now configure a shortcut to remove the word to the right of the cursor in the editor. Has the functionality like pressing ctrl+del. 
Also added a description with the corresponding German translation for the settings page for the delete-next-word and delete-previous-word action.
> Added delete-next-word action. Deletes word to the right of the cursor.

- bluej/src/main/java/bluej/editor/base/BackgroundItem.java
- bluej/src/main/java/bluej/editor/base/TextLine.java
- bluej/src/main/java/bluej/terminal/TerminalTextPane.java
This fixes a bug I found in the recent terminal change, and adds an optimisation.
We were getting caught in a layout loop while trying to calculate backgrounds for terminal lines that were off-screen, which would cause a big slowdown.  I also realised we should not be trying to swap the backgrounds if they are the same, which will also reduce the number of layouts needed.
> Fix terminal display layout loop

- bluej/src/main/java/bluej/stride/framedjava/frames/TryFrame.java
- bluej/src/main/java/bluej/stride/generic/FrameCursor.java
To match the change done in Strype, we change the behaviour of deleting a joint frame (multicanvas frame with more than the root) when hitting the backspace key and being below the structure. Instead of deleting the complete structure, we now delete the last joint frame of that structure.
This pull request also contains a fix in the location description for finally (of try frames) used for the accessibility.
> Behaviour change in deleting a joint frame with backspace

- bluej/package/build.xml
- bluej/package/greenfoot-build.xml
- bluej/src/main/java/bluej/parser/ParseUtils.java
- bluej/src/main/java/bluej/pkgmgr/Package.java
- version.properties
Several separate bug fixes for BlueJ.  The main two are an issue (reported in the Blueroom) with old inner classes causing an uncaught exception, and the issue observed in Blackbox where empty files could be recompiled endlessly.
> Small BlueJ bug fixes

- bluej/src/main/java/bluej/terminal/Terminal.java
- bluej/src/main/java/bluej/terminal/TerminalTextPane.java
During testing for BlueJ 5.3.0RC2 I noticed a weird behaviour where the terminal window would suddenly come to the front.  It took a while to work out the reason, but I happened across a tooltip bug report that explained that showing a tooltip in FX brings the window to the front.  So I've added some code that removes the tooltip when the window isn't focused to avoid this issue -- see also the long comment in the code.
> Fix a bug with the terminal tooltip causing the window to pop to the front if you mouse over it

- bluej/src/main/java/bluej/editor/base/BackgroundItem.java
- bluej/src/main/java/bluej/editor/base/TextLine.java
- bluej/src/main/java/bluej/editor/flow/JavaSyntaxView.java
- bluej/src/main/java/bluej/pkgmgr/target/ClassTarget.java
Found the cause of Michael's scope highlighting bug.  From the commit: "Fixed a bug in the scope highlighting where we could try to set a scope box as a background item for two lines at once, which would result it being removed from the first line and added to the second.
We now detect this case and copy the box if we are trying to set it to a second place."
Plus two other small tidy-ups.
> Fix scope highlighting

- bluej/src/main/java/bluej/parser/TextParser.java
- bluej/src/main/java/bluej/stride/framedjava/slots/InfixStructured.java
- bluej/src/main/java/bluej/stride/framedjava/slots/StructuredSlot.java
- bluej/src/main/java/bluej/utility/javafx/DelegableScalableTextField.java
- bluej/src/main/java/bluej/utility/javafx/TextFieldDelegate.java
We discovered that IME wasn't working in Stride, because we process edit events differently there, and it was interfering with how IME works.  This change handles IME events ourselves so that we can separate it from all of Stride's unique processing of edits.
Fixes #2335
> Fix IME entry in Stride

- greenfoot/build.gradle
- greenfoot/src/main/java/greenfoot/core/WorldHandler.java
- greenfoot/src/main/java/greenfoot/guifx/GreenfootStage.java
- greenfoot/src/main/java/greenfoot/vmcomm/VMCommsMain.java
- greenfoot/src/main/java/greenfoot/vmcomm/VMCommsSimulation.java
As mentioned in the meeting, fixes two bugs:
- Positions sometimes being a few pixels off when saving the world
- Repeatedly saving the world causing an odd state until you defocused and focused the window.
> Fix world save

- bluej/package/build.xml
- bluej/package/greenfoot-build.xml
Java 7 is no longer supported as a target on JDK 21 (and 8 seems a reasonable baseline).
> Updated minimum installer version to Java 8

- bluej/package/sign-mac.sh
They are currently not included in the Temurin JDK on Mac, as per https://github.com/adoptium/adoptium-support/issues/937
> Stop trying to fiddle with the .jsa files on Mac

- bluej/src/main/java/bluej/parser/JavaParser.java
- bluej/src/test/java/bluej/parser/BasicParseTest.java
In looking at the parsing for the new Java 21 features, I discovered a couple of cases where the parser is not handling existing Java 17 features correctly, so this is a small change to fix those (which I'm sending first, to avoid getting confused with the support for the new features).
> Fix existing switch parsing

- bluej/lib/stylesheets/flow.css
- bluej/package/winlaunch/bjmanifest.xml
- bluej/package/winlaunch/bluej-version.rc
- bluej/package/winsetup/bluej.wxs
- bluej/src/main/java/bluej/editor/base/TextLine.java
- bluej/src/main/java/bluej/editor/flow/FlowEditor.java
- bluej/src/main/java/bluej/editor/flow/FlowEditorPane.java
- bluej/src/main/java/bluej/utility/javafx/DelegableScalableTextField.java
- boot/src/main/java/bluej/Boot.java
- version.properties
As discussed recently...  The problem with the Korean IME in Java was the same as the recent Stride problem with Chinese IME (https://github.com/k-pet-group/BlueJ-Greenfoot/pull/2340) so the fix is very similar too.  The main extra change is that because it's easier in our own editor, I've added a highlight on the composite character being edited.
I'm not 100% sure about some of the behaviour but it does at least match the behaviour of standard text fields in Java, for better or worse.  For example, if you type "dud" to get a Korean character then type "." the character is replaced, although "dud" followed by <space> will keep it, which feels confusing to me.  Similarly if you type "dud" then left, the character will disappear.  But I think it's at least a lot better than it was where it …
> Fix Korean/IME input

- bluej/src/main/java/bluej/compiler/Job.java
- bluej/src/main/java/bluej/pkgmgr/Package.java
- bluej/src/main/java/bluej/pkgmgr/dependency/Dependency.java
- bluej/src/main/java/bluej/pkgmgr/dependency/ExtendsDependency.java
- bluej/src/main/java/bluej/pkgmgr/dependency/ExtendsOrImplementsDependency.java
- bluej/src/main/java/bluej/pkgmgr/dependency/ImplementsDependency.java
- bluej/src/main/java/bluej/pkgmgr/dependency/PermitsDependency.java
- bluej/src/main/java/bluej/pkgmgr/dependency/UsesDependency.java
- bluej/src/main/java/bluej/pkgmgr/target/DependentTarget.java
As discussed, fixes a bug with infinite compilation of an errorless parent sealed class, and corrects the display of a double-headed arrow between sealed parent and child.
This also has a bit of refactoring to tidy up some affected code by using the new Java 17/21 features in BlueJ's code itself: record classes and sealed classes and switch patterns.
> Fix infinite compile loop with sealed classes

- bluej/src/main/java/bluej/parser/JavaParser.java
If parsing a record pattern failed (because the user was partway through writing it, for example) the scope stack got out of shape and the parsing failed, manifesting as missing scope highlighting.
> Fix a small bug in the switch parsing

- README.md
- bluej/src/main/java/bluej/editor/flow/FlowEditorPane.java
Very small change to fix the caret not being in the right position after entry in e.g. Chinese in Windows.  Also updated the README.
> Fix IME caret position and update README

- bluej/src/main/java/bluej/terminal/TerminalTextPane.java
In BlueJ's terminal, everything after \r on the line seems to disappear when printed.  We now simply remove all \r from the output (which also means we don't need to check for it before \n).
Fixes #2357
> Fixed an issue with carriage returns causing strange visible behaviour

- .github/workflows/build-and-run-tests.yml
- .github/workflows/build-installers.yml
- README.md
- bluej/build.gradle
- bluej/package/build.xml
- bluej/package/greenfoot-build.xml
- bluej/package/sign-mac.sh
- greenfoot/build.gradle
- version.properties
This adds an Apple architecture (M1/M2) build on Github.  It's a matter of bundling the right JDK, and getting the bundler to build the right native installation.  This is easiest to do in two separate Github Actions (plus, that way they can run in parallel).  I also updated the versions of all the Github Actions (like libraries) to eliminate all the deprecation warnings.
> MacOS add Aarch64 build

- bluej/package/build.xml
- bluej/package/greenfoot-build.xml
- version.properties
This was being copied to the wrong place.
> Fix Mac Aarch Java executable path

- .github/workflows/build-installers.yml
…for the menus being bugged on Raspberry Pi's default window manager.
> Upgraded the JavaFX version on Raspberry Pi to 22.0.1 to get menu fix

- bluej/src/main/java/bluej/terminal/Terminal.java
- version.properties
We suppress the stack trace on the terminal end.
> Suppressed a JavaFX exception that Michael sees on his Mac when opening BlueJ projects

- bluej/src/main/java/bluej/Config.java
- bluej/src/main/java/bluej/editor/base/MarginAndTextLine.java
The line margin context menu (which lets you turn line numbers on/off) was not working on Windows due to mouse handling issues.
Fixes #2383.
> Fix a problem with the right-click menu on the line margin

- bluej/src/main/java/bluej/editor/flow/FlowErrorManager.java
- bluej/src/main/java/bluej/utility/BackgroundSupplier.java
- bluej/src/main/java/bluej/utility/ImportScanner.java
It seems like there were two causes for this.  One is that an exception thrown (which I'm still digging into, as it seems to have happened on Windows where the Windows installed version is using a mixture of JavaFX versions) while scanning the imports would stop quick fixes being calculated, and the other is that if quick fixes were not available (either permanently, or temporarily while BlueJ is still loading up and working out imports the first time) then the errors wouldn't show at all.
Fixes #2392
> Fix errors not being shown in Java editor

- bluej/src/main/java/bluej/stride/framedjava/frames/StrideDictionary.java
Fix incorrect help text on Stride cheat sheet for abstract method creation. Without this fix the Stride cheat sheet incorrectly displays "stride.dictionary.abstarct.name" instead of the intended, localisable, help text "Abstract method".
> Fix incorrect help text on Stride cheat sheet 

- bluej/package/winsetup/bluej.wxs
- bluej/package/winsetup/ui.wxs
- boot/build.gradle
- version.properties
We had a bug where it was possible to install multiple versions of BlueJ when using the per-machine (for-all-users) install.  This was because the detection of existing installations was happening before the point where the installing user chooses per-user/per-machine, so it would only ever look for per-user installs.  We now do the check (again) later in the process so we pick up the existing per-machine installs.
> Fix MSI upgrade in per-machine install

- bluej/package/greenfoot-build.xml
- bluej/package/winlaunch/bjmanifest.xml
- bluej/package/winlaunch/bluej-version.rc
- bluej/package/winsetup/bluej.wxs
- bluej/package/winsetup/greenfoot.wxs
- boot/build.gradle
- boot/src/main/java/bluej/Boot.java
- version.properties
This mainly includes the fix for upgrading per-machine installations on Windows.
> Update Greenfoot build to match recent BlueJ changes

- bluej/src/main/java/bluej/prefmgr/InterfacePanel.java
> Stopped an exception being thrown if you used the settings dialog without a project open.

- bluej/package/build.xml
- bluej/package/greenfoot-build.xml
- boot/src/main/java/bluej/Boot.java
- greenfoot/src/main/java/greenfoot/vmcomm/GreenfootDebugHandler.java
A collection of small unrelated commits: fix an issue with the green "you are here" annotation remaining when you're debugging but then click Reset in Greenfoot; improve the Mac error message (with a slight hack, because its an error message from the app bundler we use, not our message directly) when you try to run the Apple silicon build on an Intel Mac.
> Several tidy-ups

- bluej/build.gradle
JGit now needs SSH declared in a separate directory.
> Added missing JGit-SSH library.

- bluej/lib/german/labels
"Benutzeroberflöche" should actually be "Benutzeroberfläche".
> fix typo in german translation

- .env
- .github/workflows/build-installers.yml
- bluej/build.gradle
- bluej/lib/english/labels
- bluej/lib/korean/labels
- bluej/lib/portuguese/labels
- bluej/lib/stylesheets/dialogs.css
- bluej/lib/stylesheets/flow.css
- bluej/src/main/java/bluej/editor/base/BaseEditorPane.java
- bluej/src/main/java/bluej/editor/base/LineDisplay.java
- bluej/src/main/java/bluej/editor/flow/FlowEditor.java
- bluej/src/main/java/bluej/editor/flow/FlowEditorPane.java
- bluej/src/main/java/bluej/pkgmgr/NewTextFileDialog.java
- bluej/src/main/java/bluej/pkgmgr/PackageEditor.java
- bluej/src/main/java/bluej/pkgmgr/PkgMgrFrame.java
- bluej/src/main/java/bluej/pkgmgr/actions/NewTextFileAction.java
- bluej/src/main/java/bluej/utility/javafx/JavaFXUtil.java
- bluej/src/main/java/bluej/utility/javafx/dialog/InputDialog.java
- boot/build.gradle
- greenfoot/build.gradle
This is two main features, in the two biggest commits:
- Add a context menu command to screenshot the currently selected lines.  Copies a screenshot to the clipboard, clipped to just be the lines currently selected (and on screen).
- Change the "New CSS File..." menu command to be "New Text File..." where the user can create a CSS file, but also .txt, .md, or whatever else they put in the preferences as a file type that BlueJ should support as plain text.
> Screenshot feature plus new text file

- greenfoot/src/main/java/greenfoot/collision/ibsp/IBSPColChecker.java
It would appear flaky for cellSizes other than 1.  It was looking from the top-left edge of the cell rather than the centre, and depending on exact pixel rounding (e.g. odd image sizes vs even) and binary space tree construction, this would sometimes not return things it should have.  A search of the code found that every other instance of "x * cellSize" also added half the cell size to get to the centre -- except this one case.  So quite a simple fix in the end.
Fixes #2457
> Fix a bug in Actor.getNeighbours sometimes not working correctly
